/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountLoyaltyRouteImport } from './routes/account.loyalty'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountReservationsRouteImport } from './routes/account.reservations'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminGuestsRouteImport } from './routes/admin.guests'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoyaltyRoute = AccountLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReservationsRoute = AccountReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/reservation'
    | '/services'
    | '/account/loyalty'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/brands'
    | '/admin/careers'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/news'
    | '/admin/reservations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/reservation'
    | '/services'
    | '/account/loyalty'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/brands'
    | '/admin/careers'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/news'
    | '/admin/reservations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brands'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/reservation'
    | '/services'
    | '/account/loyalty'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/brands'
    | '/admin/careers'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/news'
    | '/admin/reservations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/account/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ReservationRoute: typeof ReservationRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/loyalty': {
      id: '/account/loyalty'
      path: '/loyalty'
      fullPath: '/account/loyalty'
      preLoaderRoute: typeof AccountLoyaltyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reservations': {
      id: '/account/reservations'
      path: '/reservations'
      fullPath: '/account/reservations'
      preLoaderRoute: typeof AccountReservationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountLoyaltyRoute: typeof AccountLoyaltyRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReservationsRoute: typeof AccountReservationsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountLoyaltyRoute: AccountLoyaltyRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReservationsRoute: AccountReservationsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BrandsRoute: BrandsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ReservationRoute: ReservationRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
